/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package factory;

import factory.java.factory.Warehouse;
import org.junit.Test;

public class AppTest {
    @Test public void canConstructWarehouse() {
        Warehouse warehouse = new Warehouse("My warehouse", null);
    }
}
